// Code generated by gfrd-gen. DO NOT EDIT.
// Table: sys_dept (系统部门表)

import request from '@/utils/request'
import type { PageParams, PageResult } from '@/utils/request/types'
import type { Dept, DeptEditDTO } from './types'
/**
 * 获取系统部门表列表
 */
export function DeptList(params: PageParams & {
  name?: string
  code?: string
  status?: number
}): Promise<PageResult<Dept>> {
  return request({
    url: '/sys/dept/list',
    method: 'get',
    params,
  })
}
/**
 * 获取系统部门表详情
 */
export function DeptView(id: number): Promise<Dept> {
  return request({
    url: '/sys/dept/view',
    method: 'get',
    params: { id },
  })
}
/**
 * 添加系统部门表
 */
export function DeptAdd(data: DeptEditDTO): Promise<void> {
  return request({
    url: '/sys/dept/add',
    method: 'post',
    data,
  })
}
/**
 * 修改系统部门表
 */
export function DeptEdit(data: DeptEditDTO): Promise<void> {
  return request({
    url: '/sys/dept/edit',
    method: 'post',
    data,
  })
}
/**
 * 删除系统部门表
 */
export function DeptDelete(id: number): Promise<void> {
  return request({
    url: '/sys/dept/delete',
    method: 'post',
    params: { id },
  })
}
