// Code generated by gfrd-gen. DO NOT EDIT.
// Table: sys_dept (系统部门表)
/**
 * 系统部门表数据类型
 */
export interface Dept {
  id: number // 部门 ID
  parentId: number // 父部门 ID
  name: string // 部门名称
  code: string // 部门编码
  leader: string // 负责人
  phone: string // 联系电话
  email: string // 邮箱
  status: number // 状态 (1 正常 0 禁用)
  sort: number // 排序
  remark: string // 备注
  createdAt: string // 创建时间
  updatedAt: string // 更新时间
  deletedAt: string // 删除时间
}

/**
 * 系统部门表编辑数据类型
 */
export interface DeptEditDTO {
  parentId: number // 父部门 ID
  name: string // 部门名称
  code: string // 部门编码
  leader: string // 负责人
  phone: string // 联系电话
  email: string // 邮箱
  status: number // 状态 (1 正常 0 禁用)
  sort: number // 排序
  remark: string // 备注
}

/**
 * 系统部门表查询参数
 */
export interface DeptListParams {
  page?: number
  size?: number
  name?: string
  code?: string
  status?: number
}
