// Code generated by gfrd-gen. DO NOT EDIT.
// Route registration for 系统部门表

package genrouter

import (
	"context"

	"github.com/gogf/gf/v2/net/ghttp"
	"sys/internal/controller/sys"
)

// RegisterDept 注册系统部门表路由
func RegisterDept(ctx context.Context, group *ghttp.RouterGroup) {
	group.Group("/dept", func(group *ghttp.RouterGroup) {
		group.Bind(sys.Dept.List)
		group.Bind(sys.Dept.View)
		group.Bind(sys.Dept.Add)
		group.Bind(sys.Dept.Edit)
		group.Bind(sys.Dept.Delete)
	})
}
