-- Code generated by gfrd-gen. DO NOT EDIT.
-- Table: sys_dept (系统部门表)
-- Menu SQL for 系统部门表 management

-- 插入菜单
INSERT INTO `sys_menu` (`pid`, `name`, `title`, `path`, `component`, `redirect`, `icon`, `type`, `permissions`, `permission_name`, `sort`, `status`, `created_at`, `updated_at`)
VALUES
  (
    (SELECT id FROM sys_menu WHERE name = 'system' LIMIT 1), -- 父菜单：系统管理
    'dept',
    '系统部门表管理',
    '/sys/dept',
    '/sys/dept/index',
    NULL,
    'material-symbols:folder-shared-outline',
    2,
    '',
    '',
    1,
    1,
    NOW(),
    NOW()
  );

-- 插入按钮权限
SET @parent_id = LAST_INSERT_ID();

-- 列表权限
INSERT INTO `sys_menu` (`pid`, `name`, `title`, `path`, `component`, `icon`, `type`, `permissions`, `permission_name`, `sort`, `status`, `created_at`, `updated_at`)
VALUES (
  @parent_id,
  'dept_list',
  '系统部门表列表',
  '',
  '',
  '',
  3,
  '/sys/dept/list',
  'sys:dept:list',
  1,
  1,
  NOW(),
  NOW()
);

-- 新增权限
INSERT INTO `sys_menu` (`pid`, `name`, `title`, `path`, `component`, `icon`, `type`, `permissions`, `permission_name`, `sort`, `status`, `created_at`, `updated_at`)
VALUES (
  @parent_id,
  'dept_add',
  '新增系统部门表',
  '',
  '',
  '',
  3,
  '/sys/dept/add',
  'sys:dept:add',
  2,
  1,
  NOW(),
  NOW()
);

-- 修改权限
INSERT INTO `sys_menu` (`pid`, `name`, `title`, `path`, `component`, `icon`, `type`, `permissions`, `permission_name`, `sort`, `status`, `created_at`, `updated_at`)
VALUES (
  @parent_id,
  'dept_edit',
  '修改系统部门表',
  '',
  '',
  '',
  3,
  '/sys/dept/edit',
  'sys:dept:edit',
  3,
  1,
  NOW(),
  NOW()
);

-- 删除权限
INSERT INTO `sys_menu` (`pid`, `name`, `title`, `path`, `component`, `icon`, `type`, `permissions`, `permission_name`, `sort`, `status`, `created_at`, `updated_at`)
VALUES (
  @parent_id,
  'dept_delete',
  '删除系统部门表',
  '',
  '',
  '',
  3,
  '/sys/dept/delete',
  'sys:dept:delete',
  4,
  1,
  NOW(),
  NOW()
);

-- 查看详情权限
INSERT INTO `sys_menu` (`pid`, `name`, `title`, `path`, `component`, `icon`, `type`, `permissions`, `permission_name`, `sort`, `status`, `created_at`, `updated_at`)
VALUES (
  @parent_id,
  'dept_view',
  '查看系统部门表详情',
  '',
  '',
  '',
  3,
  '/sys/dept/view',
  'sys:dept:view',
  5,
  1,
  NOW(),
  NOW()
);
