<!-- Code generated by gfrd-gen. DO NOT EDIT. -->
<!-- Table: sys_dept (系统部门表) -->

<script setup lang="ts">
import { ref, watch } from 'vue'
import { NModal, NForm, NFormItem, NInput, NButton, NSpace, useMessage } from 'naive-ui'
import type { Dept, DeptEditDTO } from '@/api/sys/dept/types'
import { DeptAdd, DeptEdit } from '@/api/sys/dept'

interface Props {
  modelValue?: boolean
  data?: Dept | null
}

const props = withDefaults(defineProps<Props>(), {
  modelValue: false,
  data: null,
})

const emit = defineEmits<{
  (e: 'update:modelValue', value: boolean): void
  (e: 'success'): void
}>()

const message = useMessage()
const modalVisible = ref(false)
const formRef = ref<any>(null)
const loading = ref(false)

// 表单数据
const formData = ref<DeptEditDTO>({})

// 表单验证规则
const rules = {
  name: { required: true, message: '请输入部门名称', trigger: 'blur' },
}

// 监听弹窗显示
watch(
  () => props.modelValue,
  (val) => {
    modalVisible.value = val
    if (val && props.data) {
      // 编辑模式，填充表单数据
      formData.value = { ...props.data }
    } else {
      // 新增模式，重置表单
      formData.value = {}
    }
  },
  { immediate: true }
)

// 监听弹窗关闭
watch(modalVisible, (val) => {
  emit('update:modelValue', val)
})

// 提交表单
const handleSubmit = async () => {
  try {
    await formRef.value?.validate()
    loading.value = true

    if (formData.value.id) {
      // 编辑
      await DeptEdit(formData.value as DeptEditDTO)
      message.success('编辑成功')
    } else {
      // 新增
      await DeptAdd(formData.value as DeptEditDTO)
      message.success('添加成功')
    }

    modalVisible.value = false
    emit('success')
  } catch (error: any) {
    message.error(error.message || '操作失败')
  } finally {
    loading.value = false
  }
}

// 打开弹窗
const open = (data?: Dept | null) => {
  modalVisible.value = true
  if (data) {
    formData.value = { ...data }
  } else {
    formData.value = {}
  }
}

defineExpose({ open })
</script>

<template>
  <NModal
    v-model:show="modalVisible"
    preset="card"
    title="系统部门表 - 编辑/新增"
    style="width: 600px"
    :close-on-esc="false"
  >
    <NForm
      ref="formRef"
      :model="formData"
      :rules="rules"
      label-placement="left"
      label-width:="100"
    >
      <NFormItem label="父部门 ID" path="parentId">
        <NInput
          v-model:value="formData.parentId"
          placeholder="请输入父部门 ID"
          :maxlength="50"
        />
      </NFormItem>
      <NFormItem label="部门名称" path="name">
        <NInput
          v-model:value="formData.name"
          placeholder="请输入部门名称"
          :maxlength="50"
        />
      </NFormItem>
      <NFormItem label="部门编码" path="code">
        <NInput
          v-model:value="formData.code"
          placeholder="请输入部门编码"
          :maxlength="50"
        />
      </NFormItem>
      <NFormItem label="负责人" path="leader">
        <NInput
          v-model:value="formData.leader"
          placeholder="请输入负责人"
          :maxlength="50"
        />
      </NFormItem>
      <NFormItem label="联系电话" path="phone">
        <NInput
          v-model:value="formData.phone"
          placeholder="请输入联系电话"
          :maxlength="50"
        />
      </NFormItem>
      <NFormItem label="邮箱" path="email">
        <NInput
          v-model:value="formData.email"
          placeholder="请输入邮箱"
          :maxlength="50"
        />
      </NFormItem>
      <NFormItem label="状态 (1 正常 0 禁用)" path="status">
        <NSwitch v-model:value="formData.status" />
      </NFormItem>
      <NFormItem label="排序" path="sort">
        <NInput
          v-model:value="formData.sort"
          placeholder="请输入排序"
          :maxlength="50"
        />
      </NFormItem>
      <NFormItem label="备注" path="remark">
        <NInput
          v-model:value="formData.remark"
          type="textarea"
          placeholder="请输入备注"
          :maxlength="0"
          show-count
        />
      </NFormItem>
    </NForm>

    <template #footer>
      <NSpace justify="end">
        <NButton @click="modalVisible = false">取消</NButton>
        <NButton type="primary" :loading="loading" @click="handleSubmit">确定</NButton>
      </NSpace>
    </template>
  </NModal>
</template>
