<!-- Code generated by gfrd-gen. DO NOT EDIT. -->
<!-- Table: sys_dept (系统部门表) -->

<script setup lang="ts">
import { ref, h } from 'vue'
import { NButton, NPopconfirm, NModal, NForm, NFormItem, NInput } from 'naive-ui'
import { BasicTable, type columnsType } from '@/components/BasicTable'
import { useCRUD } from '@/hooks/core/useCRUD'
import * as api from '@/api/sys/dept'
import type { Dept } from '@/api/sys/dept/types'
import EditForm from './edit.vue'

const modalRef = ref<any>(null)

const {
  loading,
  data: list,
  total,
  fetchList,
  handleDelete,
} = useCRUD<Dept>({
  api,
  message: { success: '操作成功', error: '操作失败' },
})

// 表格列配置
const columns: columnsType = [
  {
    title: '部门名称',
    key: 'name',
    width: 150,
  },
  {
    title: '部门编码',
    key: 'code',
    width: 150,
  },
  {
    title: '负责人',
    key: 'leader',
    width: 150,
  },
  {
    title: '状态 (1 正常 0 禁用)',
    key: 'status',
    width: 150,
    render: (row) => h('span', row.status ? '是' : '否'),
  },
  {
    title: '创建时间',
    key: 'createdAt',
    width: 150,
  },
  {
    title: '操作',
    key: 'action',
    width: 180,
    fixed: 'right',
    render: (row: Dept) => h('div', { style: { display: 'flex', gap: '8px' } }, [
      h(NButton, {
        size: 'small',
        type: 'primary',
        onClick: () => modalRef.value?.open(row),
      }, { default: () => '编辑' }),
      h(NPopconfirm, {
        onPositiveClick: () => handleDelete(row.id),
      }, {
        trigger: () => h(NButton, { size: 'small', type: 'error' }, { default: () => '删除' }),
        default: () => '确定删除吗？',
      }),
    ]),
  },
]

// 搜索表单
const searchFormRef = ref<any>(null)
const searchForm = ref({
  name: undefined as any,
  code: undefined as any,
  status: undefined as any,
})

const handleSearch = () => {
  fetchList(searchForm.value)
}

const handleReset = () => {
  searchFormRef.value?.restoreValidation()
  Object.keys(searchForm.value).forEach(key => {
    searchForm.value[key] = undefined
  })
  fetchList({})
}
</script>

<template>
  <n-card :bordered="false">
    <n-space vertical>
      <!-- 搜索表单 -->
      <n-form ref="searchFormRef" inline :model="searchForm" label-width="80">
        <n-flex>
          <n-form-item label="部门名称" :path="'name'">
            <n-input v-model:value="searchForm.name" placeholder="请输入" clearable style="width: 200px" />
          </n-form-item>
          <n-form-item label="部门编码" :path="'code'">
            <n-input v-model:value="searchForm.code" placeholder="请输入" clearable style="width: 200px" />
          </n-form-item>
          <n-form-item label="状态 (1 正常 0 禁用)" :path="'status'">
            <n-input v-model:value="searchForm.status" placeholder="请输入" clearable style="width: 200px" />
          </n-form-item>
        </n-flex>
        <n-form-item>
          <n-space>
            <n-button type="primary" @click="handleSearch">查询</n-button>
            <n-button @click="handleReset">重置</n-button>
          </n-space>
        </n-form-item>
      </n-form>

      <!-- 数据表格 -->
      <BasicTable
        :columns="columns"
        :data="list"
        :loading="loading"
        :pagination="{ total, showSizeChanger: true, showQuickJumper: true }"
        :remote="true"
        @update:page="fetchList"
      >
        <template #tableTitle>
          <n-button type="primary" @click="modalRef?.open()">
            <template #icon>
              <svg-icon name="add" />
            </template>
            新增
          </n-button>
        </template>
      </BasicTable>
    </n-space>
  </n-card>

  <!-- 编辑弹窗 -->
  <EditForm ref="modalRef" @success="fetchList({})" />
</template>

<style scoped>
:deep(.n-form-item) {
  margin-bottom: 12px;
}
</style>
