// Code generated by gfrd-gen. DO NOT EDIT.
// Table: sys_dept (系统部门表)

package sys

import (
	"github.com/gogf/gf/v2/frame/g"
)
// ListReq 获取系统部门表列表
type ListReq struct {
	g.Meta `path:"/sys/SysDept/list" method:"get" tags:"sys" summary:"获取系统部门表列表"`
	Page     int    `json:"page,dc:"页码" d:"1"`
	Size     int    `json:"size,dc:"每页数量" d:"10"`
	Name string `json:"name,dc:"部门名称"`
	Code string `json:"code,dc:"部门编码"`
	Status int `json:"status,dc:"状态 (1 正常 0 禁用)"`
}
type ListRes struct {
	List  interface{} `json:"list"`
	Total int         `json:"total"`
}
// AddReq 添加系统部门表
type AddReq struct {
	g.Meta `path:"/sys/SysDept/add" method:"post" tags:"sys" summary:"添加系统部门表"`
	ParentId int64 `json:"parentId,dc:"父部门 ID"`
	Name string `json:"name,dc:"部门名称"`
	Code string `json:"code,dc:"部门编码"`
	Leader string `json:"leader,dc:"负责人"`
	Phone string `json:"phone,dc:"联系电话"`
	Email string `json:"email,dc:"邮箱"`
	Status int `json:"status,dc:"状态 (1 正常 0 禁用)"`
	Sort int `json:"sort,dc:"排序"`
	Remark string `json:"remark,dc:"备注"`
}
type AddRes struct {
	g.Meta `mime:"application/json" example:"true"`
}
// EditReq 修改系统部门表
type EditReq struct {
	g.Meta `path:"/sys/SysDept/edit" method:"post" tags:"sys" summary:"修改系统部门表"`
	ParentId int64 `json:"parentId,dc:"父部门 ID"`
	Name string `json:"name,dc:"部门名称"`
	Code string `json:"code,dc:"部门编码"`
	Leader string `json:"leader,dc:"负责人"`
	Phone string `json:"phone,dc:"联系电话"`
	Email string `json:"email,dc:"邮箱"`
	Status int `json:"status,dc:"状态 (1 正常 0 禁用)"`
	Sort int `json:"sort,dc:"排序"`
	Remark string `json:"remark,dc:"备注"`
}
type EditRes struct {
	g.Meta `mime:"application/json" example:"true"`
}
// DeleteReq 删除系统部门表
type DeleteReq struct {
	g.Meta `path:"/sys/SysDept/delete" method:"post" tags:"sys" summary:"删除系统部门表"`
	Id int64 `json:"id,dc:"ID" v:"required"`
}
type DeleteRes struct {
	g.Meta `mime:"application/json" example:"true"`
}
// ViewReq 查看系统部门表详情
type ViewReq struct {
	g.Meta `path:"/sys/SysDept/view" method:"get" tags:"sys" summary:"查看系统部门表详情"`
	Id int64 `json:"id,dc:"ID" v:"required"`
}
type ViewRes struct {
	g.Meta `mime:"application/json" example:"true"`
	Data   interface{} `json:"data"`
}
