// Code generated by gfrd-gen. DO NOT EDIT.
// Table: sys_dept (系统部门表)

package sys

import (
	"context"

	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/util/gconv"
	"github.com/gogf/gf/v2/os/gtime"
)

// DeptHandler 系统部门表 Handler
type DeptHandler struct{}

// Dept 系统部门表 Handler 实例
var Dept = &DeptHandler{}
// List 系统部门表列表
func (h *DeptHandler) List(ctx context.Context, req *DeptListReq) (res *DeptListRes, err error) {
	m := g.Model("sys_dept").Ctx(ctx)

	// 构建查询条件
	if req.Name != "" {
		m = m.Where("name", req.Name)
	}
	if req.Code != "" {
		m = m.Where("code", req.Code)
	}
	if req.Status > 0 {
		m = m.Where("status", req.Status)
	}

	total, err := m.Count()
	if err != nil {
		return nil, err
	}

	var list []*Dept
	err = m.Page(req.Page, req.Size).OrderDesc("id").Scan(&list)
	if err != nil {
		return nil, err
	}

	return &DeptListRes{
		List:  list,
		Total: total,
	}, nil
}
// View 系统部门表详情
func (h *DeptHandler) View(ctx context.Context, req *DeptViewReq) (res *DeptViewRes, err error) {
	var data Dept
	err = g.Model("sys_dept").Ctx(ctx).WherePri(req.Id).Scan(&data)
	if err != nil {
		return nil, err
	}

	return &DeptViewRes{Data: data}, nil
}
// Add 添加系统部门表
func (h *DeptHandler) Add(ctx context.Context, req *DeptAddReq) (err error) {
	req.CreatedAt = gtime.Now()
	req.UpdatedAt = gtime.Now()

	_, err = g.Model("sys_dept").Ctx(ctx).Data(req).Insert()
	return err
}
// Edit 修改系统部门表
func (h *DeptHandler) Edit(ctx context.Context, req *DeptEditReq) (err error) {
	req.UpdatedAt = gtime.Now()

	_, err = g.Model("sys_dept").Ctx(ctx).WherePri(req.Id).Data(req).Update()
	return err
}
// Delete 删除系统部门表
func (h *DeptHandler) Delete(ctx context.Context, req *DeptDeleteReq) (err error) {
	// 软删除
	_, err = g.Model("sys_dept").Ctx(ctx).WherePri(req.Id).Data(g.Map{
		"deleted_at": gtime.Now(),
	}).Update()
	return err
}
